### ISSUE TITLE
upload of data in pending state

### ISSUE THREAD

**Issue by mazizij** [ihmeuw/cartodb-docker#3]
when trying to upload data it remains in a pending state
![screenshot from 2018-10-17 19-30-33](https://user-images.githubusercontent.com/40990516/47105044-2af2d800-d243-11e8-8585-e035983022f6.png)

I am not sure where to start to try and debug this error.
Any pointer would be welcomed.

**Comment by sindile** [comment]
the logs from imports.log

{"user":"username","state":"pending","tables":0,"imported_tables":0,"failed_tables":0,"error_code":null,"import_timestamp":"2018-10-27T05:03:21.714+00:00","queue_server":"84c4d39651da","database_host":"cartodb-postgis","service_name":"public_url","data_type":"file","is_sync_import":false,"import_time":0.003077,"file_stats":{},"resque_ppid":null,"user_timeout":13981,"error_source":null,"id":"e207d685-26f1-4965-8687-baf7af1de79f","total_size":0,"cartodbfy_time":0.0,"import_throughput":0.0,"cartodbfy_throughtput":null,"cartodbfy_import_ratio":0.0,"extra_options":{},"retrieved_items":0}

I then logged into the rails console

irb(main):001:0> di = DataImport['e207d685-26f1-4965-8687-baf7af1de79f'].log
D, [2018-10-27T05:36:55.457906 #533] DEBUG -- :   Sequel::Postgres::Database (2.2ms)  SELECT * FROM "data_imports" WHERE "id" = 'e207d685-26f1-4965-8687-baf7af1de79f'
D, [2018-10-27T05:36:55.461702 #533] DEBUG -- :   Sequel::Postgres::Database (1.3ms)  SELECT * FROM "logs" WHERE ("id" = 'c004611d-0d99-4a08-97e9-a7d9d7fc5af5') LIMIT 1
=> #<CartoDB::Log @values={:id=>"c004611d-0d99-4a08-97e9-a7d9d7fc5af5", :type=>"import", :user_id=>"48a8e8da-8a53-4bb2-981f-bce8a5f6121b", :created_at=>2018-10-27 05:03:21 +0000, :updated_at=>2018-10-27 05:03:26 +0000, :entries=>"2018-10-27 05:03:26 UTC: Running on server 3f0b560d360f with PID: 1776\n2018-10-27 05:03:26 UTC: new_importer()\n2018-10-27 05:03:26 UTC: Fetching datasource public_url metadata for item id public/uploads/05c04f410f3b9b15f2ae/Eastern_Cape_ASIDI_Projects_(on_2018-01-12_at_17.34.53).carto\n2018-10-27 05:03:26 UTC: File will be downloaded from public/uploads/05c04f410f3b9b15f2ae/Eastern_Cape_ASIDI_Projects_(on_2018-01-12_at_17.34.53).carto\n2018-10-27 05:03:26 UTC: Exception: undefined method `[]' for nil:NilClass\n2018-10-27 05:03:26 UTC: [\"/var/lib/gems/2.2.0/gems/uuidtools-2.1.5/lib/uuidtools.rb:603:in `block (2 levels) in first_mac'\", \"/var/lib/gems/2.2.0/gems/uuidtools-2.1.5/lib/uuidtools.rb:602:in `map'\", \"/var/lib/gems/2.2.0/gems/uuidtools-2.1.5/lib/uuidtools.rb:602:in `block in first_mac'\", \"/var/lib/gems/2.2.0/gems/uuidtools-2.1.5/lib/uuidtools.rb:608:in `call'\", \"/var/lib/gems/2.2.0/gems/uuidtools-2.1.5/lib/uuidtools.rb:608:in `first_mac'\", \"/var/lib/gems/2.2.0/gems/uuidtools-2.1.5/lib/uuidtools.rb:634:in `mac_address'\", \"/var/lib/gems/2.2.0/gems/uuidtools-2.1.5/lib/uuidtools.rb:242:in `block in timestamp_create'\", \"/var/lib/gems/2.2.0/gems/uuidtools-2.1.5/lib/uuidtools.rb:232:in `synchronize'\", \"/var/lib/gems/2.2.0/gems/uuidtools-2.1.5/lib/uuidtools.rb:232:in `timestamp_create'\", \"/cartodb/services/importer/lib/importer/job.rb:13:in `initialize'\", \"/cartodb/services/importer/lib/importer/runner.rb:414:in `new'\", \"/cartodb/services/importer/lib/importer/runner.rb:414:in `new_job'\", \"/cartodb/services/importer/lib/importer/runner.rb:53:in `initialize'\", \"/cartodb/app/models/data_import.rb:785:in `new'\", \"/cartodb/app/models/data_import.rb:785:in `new_importer_with_runner'\", \"/cartodb/app/models/data_import.rb:736:in `new_importer'\", \"/cartodb/app/models/data_import.rb:423:in `dispatch'\", \"/cartodb/app/models/data_import.rb:189:in `run_import!'\", \"/cartodb/lib/resque/importer_jobs.rb:9:in `block in perform'\", \"/cartodb/lib/resque/base_job.rb:21:in `call'\", \"/cartodb/lib/resque/base_job.rb:21:in `run_action'\", \"/cartodb/lib/resque/importer_jobs.rb:9:in `perform'\", \"/var/lib/gems/2.2.0/gems/resque-1.25.2/lib/resque/job.rb:240:in `block (3 levels) in perform'\", \"/var/lib/gems/2.2.0/gems/resque-metrics-0.1.1/lib/resque/metrics.rb:353:in `around_perform_metrics'\", \"/var/lib/gems/2.2.0/gems/resque-1.25.2/lib/resque/job.rb:239:in `block (2 levels) in perform'\", \"/var/lib/gems/2.2.0/gems/resque-1.25.2/lib/resque/job.rb:247:in `call'\", \"/var/lib/gems/2.2.0/gems/resque-1.25.2/lib/resque/job.rb:247:in `perform'\", \"/var/lib/gems/2.2.0/gems/resque-1.25.2/lib/resque/worker.rb:250:in `perform'\", \"/var/lib/gems/2.2.0/gems/resque-1.25.2/lib/resque/worker.rb:189:in `block in work'\", \"/var/lib/gems/2.2.0/gems/resque-1.25.2/lib/resque/worker.rb:166:in `loop'\", \"/var/lib/gems/2.2.0/gems/resque-1.25.2/lib/resque/worker.rb:166:in `work'\", \"/var/lib/gems/2.2.0/gems/resque-1.25.2/lib/resque/tasks.rb:41:in `block (2 levels) in <top (required)>'\", \"/var/lib/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `call'\", \"/var/lib/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `block in execute'\", \"/var/lib/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `each'\", \"/var/lib/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `execute'\", \"/var/lib/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/task.rb:158:in `block in invoke_with_call_chain'\", \"/usr/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'\", \"/var/lib/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/task.rb:151:in `invoke_with_call_chain'\", \"/var/lib/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/task.rb:144:in `invoke'\", \"/var/lib/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:116:in `invoke_task'\", \"/var/lib/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block (2 levels) in top_level'\", \"/var/lib/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `each'\", \"/var/lib/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block in top_level'\", \"/var/lib/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'\", \"/var/lib/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:88:in `top_level'\", \"/var/lib/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:66:in `block in run'\", \"/var/lib/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'\", \"/var/lib/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:63:in `run'\", \"/var/lib/gems/2.2.0/gems/rake-0.9.2.2/bin/rake:33:in `<top (required)>'\", \"/usr/local/bin/rake:23:in `load'\", \"/usr/local/bin/rake:23:in `<main>'\"]\n2018-10-27 05:03:26 UTC: ERROR!\n\n"}>

**Comment by sindile** [comment]
Following a posting to https://groups.google.com/forum/#!topic/cartodb/sEDygx8ufaA
I ran this command - UUIDTools::UUID.timestamp_create
script/rails: No such file or directory - addr
NoMethodError: undefined method `[]' for nil:NilClass
        from /var/lib/gems/2.2.0/gems/uuidtools-2.1.5/lib/uuidtools.rb:603:in `block (2 levels) in first_mac'
        from /var/lib/gems/2.2.0/gems/uuidtools-2.1.5/lib/uuidtools.rb:602:in `map'
        from /var/lib/gems/2.2.0/gems/uuidtools-2.1.5/lib/uuidtools.rb:602:in `block in first_mac'
        from /var/lib/gems/2.2.0/gems/uuidtools-2.1.5/lib/uuidtools.rb:608:in `call'
        from /var/lib/gems/2.2.0/gems/uuidtools-2.1.5/lib/uuidtools.rb:608:in `first_mac'
        from /var/lib/gems/2.2.0/gems/uuidtools-2.1.5/lib/uuidtools.rb:634:in `mac_address'
        from /var/lib/gems/2.2.0/gems/uuidtools-2.1.5/lib/uuidtools.rb:242:in `block in timestamp_create'
        from /var/lib/gems/2.2.0/gems/uuidtools-2.1.5/lib/uuidtools.rb:232:in `synchronize'
        from /var/lib/gems/2.2.0/gems/uuidtools-2.1.5/lib/uuidtools.rb:232:in `timestamp_create'
        from (irb):2
        from /var/lib/gems/2.2.0/gems/railties-4.2.10/lib/rails/commands/console.rb:110:in `start'
        from /var/lib/gems/2.2.0/gems/railties-4.2.10/lib/rails/commands/console.rb:9:in `start'
        from /var/lib/gems/2.2.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:68:in `console'
        from /var/lib/gems/2.2.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /var/lib/gems/2.2.0/gems/railties-4.2.10/lib/rails/commands.rb:17:in `<top (required)>'
        from script/rails:6:in `require'
        from script/rails:6:in `<main>'

**Comment by sindile** [comment]
This can be closed.

**Comment by davschne** [comment]
Hi, @sindile. Sorry, I guess I missed the notifications for this issue. Do you think this issue warrants any changes to this repo?

**Comment by sindile** [comment]
Hi @davschne maybe update as per https://github.com/dersteppenwolf/cartodb-docker
